# Copyright (c) Facebook, Inc. and its affiliates.
from .maskformer_transformer_decoder import StandardTransformerDecoder
#from .mask2former_transformer_decoder import MultiScaleMaskedTransformerDecoder
from .meanshiftformer_transformer_decoder import MeanShiftTransformerDecoder, PretrainedMeanShiftTransformerDecoder
